GCC = gcc
FLAG = -g -lm
OBJ = test.o cmp.o

all: test

test: $(OBJ)
	$(GCC) $(OBJ) -o $@ $(FLAG)

test.o: test.c
	$(GCC) $< -c -o $@ $(FLAG)

cmp.o: cmp.c cmp.h pool.h defines.h chunk.h
	$(GCC) $< -c -o $@ $(FLAG)

clean:
	rm -f test $(OBJ)
